### ISSUE TITLE
[issue] 로그아웃할 때 dispatch가 여러번 실행되고 올바르게 로그아웃이 진행되지 않음

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#145]
## 요약
로그아웃할 때 콘솔이 난리남

## 재현 방법
1. 로그인
2. 로그인 후 탑 화면으로 돌아온 후 , 마이페이지로 이동
3. 로그아웃 버튼 클릭
4. 다음과 같은 에러가 발생
```
authContext.js:17 Uncaught TypeError: Cannot read properties of undefined (reading 'isLoggedIn')
    at AuthReducer (authContext.js:17:1)
    at updateReducer (react-dom.development.js:16664:1)
    at Object.useReducer (react-dom.development.js:17898:1)
    at useReducer (react.development.js:1626:1)
    at AuthContextProvider (authContext.js:51:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
```

## 수정 내용
dispatch를 useEffect안에 넣는다?🤔
[여기보고](https://codesandbox.io/s/login-authentication-usecontext-66t9t?file=/src/Context/actions.js) 참고해서 작성한 컨텍스트인데 다시 자세히 뜯어봐야할 듯

**Comment by mdgarden** [comment]
로그인은 잘 되는데 로그아웃에서 문제가 발생하는 이유를 잘 모르겠음

**Comment by mdgarden** [comment]
reducer에서 switch문을 쓰는 이유를 이제서야 깨달았읍니다.......
