### ISSUE TITLE
[issue] useContext가 불러온 값이 null

### ISSUE THREAD

**Issue by mdgarden** [EasyAndBeauty/DailyReceipt-FE-WEB#152]
## 요약
AuthClient를 실제로 연결해보면 useContext의 값이 null이라는 에러가 뜸

## 재현방법
아무 파일에서나 todoClient안에 있는 함수를 호출함

## 에러 로그

```
react.development.js:209 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
printWarning @ react.development.js:209
error @ react.development.js:183
resolveDispatcher @ react.development.js:1592
useContext @ react.development.js:1602
useAuthState @ authContext.js:33
RefreshToken @ client.js:64
AuthClient @ client.js:27
./src/controllers/todoController.js @ todoController.js:3
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/components/pages/TodoPage/TodoPage.jsx @ index.js:1
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/components/pages/TodoPage/index.js @ TodoPage.styles.jsx:51
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/components/index.js @ index.js:1
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/App.js @ todo_check_icon.svg:33
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/index.js @ useLocalStorage.jsx:12
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
Show 2 more frames


react.development.js:1618 Uncaught TypeError: Cannot read properties of null (reading 'useContext')
    at useContext (react.development.js:1618:1)
    at useAuthState (authContext.js:33:1)
    at RefreshToken (client.js:64:1)
    at AuthClient (client.js:27:1)
    at ./src/controllers/todoController.js (todoController.js:3:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/components/pages/TodoPage/TodoPage.jsx (index.js:1:1)
    at options.factory (react refresh:6:1)
```
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/66259746/191291839-9d9db945-7834-4f86-80fc-e96219a74aee.png">

**Comment by mdgarden** [comment]
지금 생각하는 원인
1. axios 안에서 context 쓰는 순서, 혹은 로직이 잘못됨
2. API호출하는 방법이 잘못됨
https://stackoverflow.com/questions/64841268/how-can-i-use-an-axios-get-call-inside-a-context-provider-in-react

**Comment by mdgarden** [comment]
https://github.com/EasyAndBeauty/DailyReceipt-FE-WEB/blob/3479f44b33edb0d056f9c6dfc718d2a122a5c4aa/src/store/authContext.js#L33

여기서 useContext가 null이래 어케 이럴수가있지?
파일 읽어오는 순서와 관련이 있는건가? 린트 오류는 안나는데 실행시에 오류가 나는건 어떤 상황에서임??

**Comment by mdgarden** [comment]
훅스의 기본을 몰라서 발생한 문제였습니다,,,,
클라이언트 불러오는 곳에서 다음과 같이 사용하시면 됩니다.

```
  const [getTodoList, postTodo, updateTodo, deleteTodo] = useTodoClient();
```

**Comment by IGhost-P** [comment]
> https://github.com/EasyAndBeauty/DailyReceipt-FE-WEB/blob/3479f44b33edb0d056f9c6dfc718d2a122a5c4aa/src/store/authContext.js#L33
> 
> 여기서 useContext가 null이래 어케 이럴수가있지? 파일 읽어오는 순서와 관련이 있는건가? 린트 오류는 안나는데 실행시에 오류가 나는건 어떤 상황에서임??
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 이거 넘 귀여운 모먼트
